#!/bin/bash
#variable
b='\033[34;1m'
g='\033[32;1m'
p='\033[35;1m'
c='\033[361m'
r='\033[31;1m'
w='\033[37;1m'
y='\033[33;1m'


isi(){
        url=http://ip-api.com/
        echo $y"Enter IP Target : "
        read ip
        curl -s $url$ip
        echo $y"Tools by Adiixyz "
        echo $y"Lets Go! "
}

perintah(){
         echo $g"Enter your nickname : "
         read nick
         echo $g"Hi $nick "
         echo $y"Want to explore deeper ? "
         read -p "y/n" piII
         if [ $piII = "y" ]; then
                 clear
                 banner
                 isi
         else
                 echo $r"Kesalahan"
                 exit
          fi
}


banner(){
    echo $b"================ADIIXYZ================"
    sleep 1
    echo $y"Author : Adii_Andre "
    sleep 1
    echo $y"Yntkts "
    sleep 1
    echo $y" WhatsApp 6281111111111"
    sleep 1
    echo $b"=================ADIIXYZ================"
     sleep 1
     echo ""
}
perintah
